[package]
name = "quarchitect"
version = "0.8.0"
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.8.7"
nom = "5.1.2"
rayon = "1.3.1"